# version: '3'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: imags-lib-backed:latest # 镜像名称
#    environment:
#      JVM_OPTS: "-Xmx256m -Xms32m "
#      SPRING_PROFILES_ACTIVE: prod
#    restart: always  # 总是重启
#    container_name: imags-lib-backed #容器名称
#    ports:    # 指定端口映射
#      - "8123:8123"
#

#初步想法是一个镜像，imags-lib-all，后端，数据库，缓存都放在不同的容器里面，但是使用的都是同一个镜像




services:
  app:
    image: imags-lib-all:latest
    container_name: imags-lib-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8123"
    environment:
      - SERVICE=app
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /usr/local/projects/imags-lib-all/imags-lib-backend:/usr/local/projects/imags-lib-all/imags-lib-backend
    restart: always  # 总是重启
    networks:
      - app_network

networks:
  app_network:
    driver: bridge


#services:
#  app:
#    image: imags-lib-all:latest
#    container_name: imags-lib-backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - SERVICE=app
#      - SPRING_PROFILES_ACTIVE=prod
#    ports:
#      - "8123:8123"
#    volumes:
#      - /usr/local/projects/imags-lib-all/imags-lib-backend:/usr/local/projects/imags-lib-all/imags-lib-backend
#    depends_on:
#      - mysql
#      - redis
#
#  mysql:
#    image: imags-lib-all:latest
#    container_name: mysql-db
#    environment:
#      - SERVICE=mysql
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=shizhan
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=root
#    ports:
#      - "3307:3307"
#    volumes:
#      - /usr/local/projects/imags-lib-all/mysql-db:/usr/local/projects/imags-lib-all/mysql-db
#
#  redis:
#    image: imags-lib-all:latest
#    container_name: redis-cache
#    environment:
#      - SERVICE=redis
#    ports:
#      - "6380:6380"
#    volumes:
#      - /usr/local/projects/imags-lib-all/redis-cache:/usr/local/projects/imags-lib-all/redis-cache


