name: Deploy to Server

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER_PASS }}" > ~/.ssh/server_key
          chmod 600 ~/.ssh/server_key
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SERVER_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            docker build -t imags-lib:latest .
            docker stop imags-lib || true
            docker rm imags-lib || true
            docker run -d -p 8123:8123 --name imags-lib imags-lib:latest
          EOF
